Fix issue with missing identifier from ActiveRecord
WeTransfer/wt_activerecord_index_spy pull request #21
Opened 2021-06-15 16:58 UTC by lloydwatkin

## Description

If `ActiveRecord` does not provide an identifier this causes the output to fail. This update simply stringifies the identifier so a crash does not happen.

Fixes #19

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

* Locally using code which currently fails
* Unit test added

## Checklist:

- [x] My code follows the style guidelines set by rubocop
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2021-06-15 19:43 UTC, fabioperrella requested changes
Hey @lloydwatkin , thanks for your contribution!! Could you pls check the errors on CI?

2021-06-15 19:53 UTC, lloydwatkin commented
Yeah looks like I didn't use valid postgesql syntax (only have mySQL locally). Will get this fixed up tomorrow morning 👍

2021-06-16 19:21 UTC, fabioperrella commented on spec/lib/wt_activerecord_index_spy/notification_listener_spec.rb
> +    it 'defaults to empty string if identifier not provided' do
This test is still broken for Postgres. I think you have to do these things:
- change double quotes by single quotes
```diff
-'SELECT * FROM users WHERE name = "lala"'
+"SELECT * FROM users WHERE name = 'lala'"
```
- create another IT to test Postgres, because currently all results of Postgres are uncertain OR test only MySQL, which I think is ok, given the fix you did works for both

2021-06-17 07:59 UTC, lloydwatkin commented
@fabioperrella apologies, its been a while since I've worked with postgressql and I tried to use the quick route (rather than installing it and testing). All updated now :+1:

2021-06-17 09:03 UTC, fabioperrella commented
No problem!

Could you pls take a look at the failure on CI pls?

2021-06-17 09:58 UTC, lloydwatkin commented
Didn't push all local changes, now pushed.

2021-06-17 10:28 UTC, fabioperrella approved these changes
great!

2021-06-17 10:31 UTC, merged